name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ probando las acciones de GitHub ğŸš€
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
              - run: echo "ğŸ‰ El trabajo(job) se activÃ³ automÃ¡ticamente por el evento ${{ github.event_name }}."
              - run: echo "ğŸ§ Este trabajo se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado en GitHub."
              - run: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
              - name: Check out repository code
                uses: actions/checkout@v3
              - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado al runner."
              - run: echo "ğŸ–¥ï¸ El flujo de trabajo estÃ¡ ahora listo para probar su cÃ³digo en el runner(corredor)."
              - name: List files in the repository
                run: |
                  ls ${{ github.workspace }}
              - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
