name: Demo de GitHub Actions
run-name: ${{ github.actor }} estÃ¡ probando las acciones de GitHub ğŸš€
on: [push]
jobs:
    Explorando-Acciones-de-GitHub:
        runs-on: ubuntu-latest
        steps:
              - run: echo "ğŸ‰ El trabajo(job) se activÃ³ automÃ¡ticamente por el evento ${{ github.event_name }}."
              - run: echo "Pero no es el Ãºnico evento que existe y no es la Ãºnica forma."
              - run: echo "ğŸ§ Este trabajo se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado en GitHub."
              - run: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
              - name: Consultar el cÃ³digo del repositorio
                uses: actions/checkout@v3
              - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado al runner."
              - run: echo "ğŸ–¥ï¸ El flujo de trabajo estÃ¡ ahora listo para probar su cÃ³digo en el runner(corredor)."
              - name: Listar archivos en el repositorio
                run: |
                  ls ${{ github.workspace }}
              - run: echo "ğŸ El estado de este trabajo es -> ${{ job.status }}."
